"use client";

import Link from "next/link";

export default function MfaSettingsPage() {
  return (
    <div className="space-y-6 max-w-4xl">
      {/* Breadcrumb & Header */}
      <div>
        <div className="flex items-center gap-2 text-xs text-gray-500 dark:text-slate-400 mb-1">
          <Link href="/settings" className="hover:text-emerald-500 transition">Settings</Link>
          <span>/</span>
          <Link href="/settings/security" className="hover:text-emerald-500 transition">Security</Link>
          <span>/</span>
          <span className="text-gray-900 dark:text-white font-medium">MFA</span>
        </div>
        <div className="flex items-center gap-3">
          <h1 className="text-2xl font-bold text-gray-900 dark:text-white">Multi-Factor Authentication (MFA)</h1>
          <span className="px-2.5 py-0.5 rounded-full text-xs font-semibold bg-amber-500/10 text-amber-600 dark:text-amber-400 border border-amber-500/20">
            Coming Soon
          </span>
        </div>
        <p className="text-sm text-gray-500 dark:text-slate-400 mt-1">
          Add an extra layer of protection to user accounts with Time-based One-Time Passwords (TOTP).
        </p>
      </div>

      {/* Main Preview Card */}
      <div className="bg-white dark:bg-slate-900 border border-gray-200 dark:border-slate-800 rounded-2xl p-6 shadow-sm space-y-6">
        <div className="flex items-start gap-4">
          <div className="w-12 h-12 rounded-xl bg-indigo-500/10 border border-indigo-500/20 flex items-center justify-center text-indigo-500 flex-shrink-0">
            <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.75} d="M9 12.75L11.25 15 15 9.75m-3-7.036A11.959 11.959 0 013.598 6 11.99 11.99 0 003 9.749c0 5.592 3.824 10.29 9 11.623 5.176-1.332 9-6.03 9-11.622 0-1.31-.21-2.571-.598-3.751h-.152c-3.196 0-6.1-1.248-8.25-3.285z" />
            </svg>
          </div>
          <div>
            <h2 className="text-base font-bold text-gray-900 dark:text-white">TOTP Authenticator Apps</h2>
            <p className="text-xs text-gray-500 dark:text-slate-400 mt-1 leading-relaxed">
              Enabling Multi-Factor Authentication requires users to provide a 6-digit verification code generated by authenticator apps (Google Authenticator, 1Password, Authy, Apple Keychain) upon signing in.
            </p>
          </div>
        </div>

        {/* Feature Roadmap & Capability Breakdown */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 pt-2">
          <div className="p-4 rounded-xl bg-gray-50 dark:bg-slate-800/50 border border-gray-200 dark:border-slate-800">
            <p className="text-xs font-bold text-gray-900 dark:text-white">Standard RFC 6238 TOTP</p>
            <p className="text-[11px] text-gray-500 dark:text-slate-400 mt-1">
              Compatible with any mobile or desktop authenticator app via QR code pairing.
            </p>
          </div>

          <div className="p-4 rounded-xl bg-gray-50 dark:bg-slate-800/50 border border-gray-200 dark:border-slate-800">
            <p className="text-xs font-bold text-gray-900 dark:text-white">Emergency Recovery Codes</p>
            <p className="text-[11px] text-gray-500 dark:text-slate-400 mt-1">
              One-time backup codes generated during setup to prevent account lockout.
            </p>
          </div>

          <div className="p-4 rounded-xl bg-gray-50 dark:bg-slate-800/50 border border-gray-200 dark:border-slate-800">
            <p className="text-xs font-bold text-gray-900 dark:text-white">Enforcement by Role</p>
            <p className="text-[11px] text-gray-500 dark:text-slate-400 mt-1">
              Require mandatory 2FA enrollment for administrative and privileged user roles.
            </p>
          </div>
        </div>

        {/* Mock UI Preview */}
        <div className="border border-dashed border-gray-200 dark:border-slate-800 rounded-xl p-5 bg-gray-50/50 dark:bg-slate-950/40 space-y-4">
          <div className="flex items-center justify-between">
            <span className="text-xs font-semibold text-gray-700 dark:text-slate-300">Enforce MFA for Administrators</span>
            <span className="px-2 py-0.5 text-[10px] font-bold rounded-md bg-gray-200 dark:bg-slate-800 text-gray-500 dark:text-slate-400 uppercase">
              Preview Mode
            </span>
          </div>
          <div className="h-2 bg-gray-200 dark:bg-slate-800 rounded-full w-2/3 animate-pulse" />
          <div className="h-2 bg-gray-200 dark:bg-slate-800 rounded-full w-1/2 animate-pulse" />
        </div>
      </div>
    </div>
  );
}
